version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_9857859

    #convert Docker port 80 to system port 8088
    ports: 
      - "8088:80"
    volumes:
      # copy src folder to Docker folder
      - ./src:/var/www/html 
      - ./.docker_config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      # - mysql
    networks:
      - laravel

  # mysql:
  #   image: mysql:5.7.22
  #   container_name: mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "4306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_76544819
    volumes:
      # copy src folder to Docker folder
      - ./src:/var/www/html
    ports:
      # php port is on 9000, it is used for nginx defaultconf
      - "9000:9000"
    networks:
      - laravel